# Programa para calcular el Índice de Masa Corporal (IMC)
peso = float(input("Ingrese su peso en kilogramos: "))
altura = float(input("Ingrese su altura en metros: "))
imc = peso / (altura ** 2)
print("Su Índice de Masa Corporal es:", imc)